# Generated by Django 4.0.3 on 2022-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_visit',
            field=models.IntegerField(default=0),
        ),
    ]
