# Generated by Django 4.0.3 on 2022-05-17 13:16

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/thumbnails/')),
                ('full_size', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/full-size/')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieimages'),
        ),
    ]
