# Generated by Django 4.0.3 on 2022-05-18 06:45

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/thumbnails/')),
                ('full_size', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/full-size/')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_url',
        ),
    ]
