# Generated by Django 4.0.3 on 2022-05-18 06:45

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieimages_alter_movie_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_url',
        ),
    ]
