# Generated by Django 4.0.3 on 2022-05-18 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieimages_remove_movie_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movieimages'),
        ),
    ]
