# Generated by Django 4.0.3 on 2022-05-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieimages_alter_movie_image_url'),
        ('movies', '0007_alter_movie_image_url'),
    ]

    operations = [
    ]
